import 'package:NetworkUtil/utils/network/networking.dart';

import 'model.dart';

///
/// generated by JsonToDart(https://plugins.jetbrains.com/plugin/12562-jsontodart-json-to-dart-) plugin and add necessary request information and [createModel] method.
///
/// * the response json from server will be
///
/// {
///   "data":{
///     "access_token":"accessToken",
///     "refresh_token":"RefreshToken"
///    },
///   "success":true
/// }
///
/// * or
///
/// {
///   "error_message":"unknown error",
///   "success":false
/// }
///

class Token extends Model {
  Token() {
    this.data = Data();
  }

  Token.fromJson(dynamic json) {
    data = json['data'] != null ? Data.fromJson(json['data']) : null;
    success = json['success'];
    errorCode = json['error_code'];
    errorMessage = json['error_message'];
  }

  Map<String, dynamic> toJson() {
    var map = <String, dynamic>{};
    if (data != null) {
      map['data'] = data?.toJson();
    }
    map['success'] = success;
    return map;
  }

  @override
  Model? createModel(dynamic json) => Token.fromJson(json);

  @override
  Map<String, dynamic> get header => Header.unLoginHeader;

  @override
  Method get method => Method.GET;

  @override
  String get url => RefreshTokenUrl;
}

class Data {
  String? accessToken;
  String? refreshToken;

  Data({this.accessToken, this.refreshToken});

  Data.fromJson(dynamic json) {
    accessToken = json["access_token"];
    refreshToken = json["refresh_token"];
  }

  Map<String, dynamic> toJson() {
    var map = <String, dynamic>{};
    if (accessToken != null) {
      map['access_token'] = accessToken;
    }
    if (refreshToken != null) {
      map['refresh_token'] = refreshToken;
    }
    return map;
  }
}
